routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['uses'=>'Auth\LoginController@showLoginForm']);
// Auth
Auth::routes();
// OAuth
Route::get('login/{provider}',          'Auth\SocialAccountsController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\SocialAccountsController@handleProviderCallback');

Route::group( ['middleware' => 'auth'], function() {
    Route::resource('users', 'UsersController');
    Route::resource('roles', 'RolesController');
    Route::get('myprofile', 'UsersController@myprofile');
    Route::post('myprofile/update/{id}', 'UsersController@profileUpdate')->name('profile.update');
    Route::get('notifications','NotificationsController@index')->name('notifications');
    Route::post('read/{id}/{application_id}','NotificationsController@markAsRead')->name('notifications.read');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use App\LinkedSocialAccount;
use Modules\Department\Entities\Department;
use Modules\Ticket\Entities\Ticket;
use Modules\Sap\Entities\Sap;
use Modules\Ticket\Entities\Reply;
use App\Profile;
use Cache;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;        

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function accounts()
    {
        return $this->hasMany(LinkedSocialAccount::class);
    }

    public function profile()
    {
        return $this->hasOne(Profile::class, 'user_id');
    }
             
    public function profileOwner($user)
    {
        return $this->id == $user->id;
    }
    
    public function tickets()
    {
        return $this->hasMany(Ticket::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\User;
use App\Role;
use App\Permission;
use App\Authorizable;
use App\Profile;
use App\Repositories\UsersRepository as UR;
use Auth;
use Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Notifications\Notification;

class UsersController extends Controller
{
    use Authorizable;
    protected $urepo;

    public function __construct(UR $urepo)
    {
        $this->urepo = $urepo;
    }

    public function index(UR $repo)
    {   
        $result = $repo->all();
        return view('backend.users.index', compact('result'));
    }

    public function create()
    {   
        $roles = Role::all();
        return view('backend.users.create', compact('roles'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'roles' => 'required|min:1'            
        ]);
        

        // hash password
        $request->merge(['password' => bcrypt($request->get('password'))]);

        // Create the user
        if ($user = User::create($request->except('roles', 'permissions'))) {
            // sync permission
            $this->syncPermissions($request, $user);            
            // user's avatar
            if ($request->hasFile('avatar')) {
                $avatar = $request->avatar;
                $avatar_new_name = time() . $avatar->getClientOriginalName();
                $avatar->move('uploads/avatars', $avatar_new_name);
            }
            $profile = new Profile;
            $profile->user_id = $user->id;
            if(!empty($avatar_new_name)){
                $profile->avatar = 'uploads/avatars/'.$avatar_new_name;
            }else{
                $profile->avatar = 'uploads/avatars/default.svg';
            }
            $profile->hod_id = $request->hod_id;
            $profile->save();

            Session::flash('success','User has been created.');
        } else {
            Session::flash('fail','Unable to create user.');
        }        
        return redirect()->route('users.index');
    }
    

    public function edit($id)
    {
        $user = User::find($id);
        $roles = Role::pluck('name', 'id');
        $permissions = Permission::all('name', 'id');        

        return view('backend.users.edit', compact('user', 'roles', 'permissions'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users,email,' . $id,
            'roles' => 'required|min:1',
        ]);

        // Get the user
        $user = User::find($id);              
        // Update user
        $user->fill($request->except('roles', 'permissions', 'password'));

        // check for password change
        if ($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        
        // user's avatar
        if ($request->hasFile('avatar')) {
            
            $avatar = $request->avatar;
            $avatar_new_name = time() . $avatar->getClientOriginalName();
            $avatar->move('uploads/avatars', $avatar_new_name);
            $user->profile->avatar = 'uploads/avatars/'.$avatar_new_name;
        }     
        if($request->has('hod_id')){
            $user->profile->hod_id = $request->hod_id;
            $user->profile->update();
        }  
        $user->save();
        $user->profile->update();
        // Handle the user roles
        $this->syncPermissions($request, $user);        
        Session::flash('success','User has been updated.');
        return redirect()->back();
    }

    public function destroy($id)
    {
        if (Auth::user()->id == $id) {
            Session::flash('warning','Deletion of currently logged in user is not allowed :(')->important();
            return redirect()->back();
        }

        if (User::findOrFail($id)->delete()) {
            Session::flash('success','User has been deleted');
        } else {
            Session::flash('success','User not deleted');
        }

        return redirect()->back();
    }

    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if (!$user->hasAllRoles($roles)) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);
        return $user;
    }

    public function myprofile(){
        $user = Auth::user();
        $user_id = Auth::id();        
        return view('backend.users.profile', compact('user'));
    }

    public function profileUpdate(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users,email,' . $id,            
        ]);

        // Get the user
        $user = User::find($id);              
        // Update user
        $user->fill($request->except('password'));

        // check for password change
        if ($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }
        
        // user's avatar
        if ($request->hasFile('avatar')) {
            
            $avatar = $request->avatar;
            $avatar_new_name = time() . $avatar->getClientOriginalName();
            $avatar->move('uploads/avatars', $avatar_new_name);
            $user->profile->avatar = 'uploads/avatars/'.$avatar_new_name;
        }     

        $user->save();
        $user->profile->update();        
        Session::flash('success','User has been updated.');
        return redirect()->back();
    }

    

    
}

resources/views/backend/users/_form.blade.php
<!-- Name Form Input -->
<div class="form-group @if ($errors->has('name')) has-error @endif">
    {!! Form::label('name', 'Name') !!} {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Name']) !!}
    @if ($errors->has('name'))
    <p class="help-block">{{ $errors->first('name') }}</p> @endif
</div>

<!-- email Form Input -->
<div class="form-group @if ($errors->has('email')) has-error @endif">
    {!! Form::label('email', 'Email') !!} {!! Form::text('email', null, ['class' => 'form-control', 'placeholder' => 'Email'])
    !!} @if ($errors->has('email'))
    <p class="help-block">{{ $errors->first('email') }}</p> @endif
</div>

<!-- password Form Input -->
<div class="form-group @if ($errors->has('password')) has-error @endif">
    {!! Form::label('password', 'Password') !!} {!! Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password'])
    !!} @if ($errors->has('password'))
    <p class="help-block">{{ $errors->first('password') }}</p> @endif
</div>
@role('Admin')
<!-- Roles Form Input -->
<div class="form-group @if ($errors->has('roles')) has-error @endif">            
    {!! Form::label('roles[]', 'Roles') !!}
    {!! Form::select('roles[]', $roles, isset($user) ? $user->roles->pluck('id')->toArray()
    : null, ['class' => 'form-control selectize', 'multiple']) !!} 
    @if($errors->has('roles'))
    <p class="help-block">{{ $errors->first('roles') }}</p>
    @endif
</div>


<!-- Permissions -->
@if(isset($user))
    @include('shared._permissions', ['closed' => 'true', 'model' => $user ]) @endif
@endrole
@include('asset-partials.selectize')

resources/views/backend/users/create.blade.php
@extends('backend.master')
@section('content')
{!! Form::open(['route' => ['users.store'], 'files'=>true ]) !!}
<div class="row">
    <div class="col-md-4">
        <div class="card card-profile">
            <div class="card-header" style="background-image: url({{asset('img/photos/bg-profile.jpg')}});"></div>
            <div class="card-body text-center">
                <img class="card-profile-img" src="{{asset('uploads/avatars/default.svg')}}" width="200px" style="background-color:#ffffff">
                <h3 class="mb-3">New User</h3>
                <div class="input-file-container text-center">
                    <input class="input-file" id="my-file" type="file" name="avatar">
                    <label tabindex="0" for="my-file" class="input-file-trigger btn btn-sm">Change profile picture</label>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-8">
        @card
        @cardHeader
        @slot('card_title') Create Users @endslot
        @endcardHeader
        @cardBody

        @include('backend.users._form')
        <div class="form-group">
            <button type="submit" class="btn btn-md btn-primary">
                @if(isset($user->id)) Update @else Create @endif
            </button>
            <a href="{{route('users.index')}}" class="btn btn-secondary">Back</a>
        </div>
        @endcardBody
        @endcard
    </div>
</div>
{!! Form::close() !!}
@endsection
@include('asset-partials.input-file')

resources/views/backend/users/edit.blade.php
@extends('backend.master') 
@section('content')
{!! Form::model($user, ['method' => 'PUT', 'route' => ['users.update', $user->id ],'files'=>true ]) !!}

<div class="row">
        <div class="col-md-4">
                <div class="card card-profile">
                  <div class="card-header" style="background-image: url({{asset('img/photos/bg-profile.jpg')}});"></div>
                  <div class="card-body text-center">
                    <img class="card-profile-img" src="{{asset($user->profile->avatar)}}">
                  <h3 class="mb-3">{{$user->name}}</h3>                    
                    <div class="input-file-container text-center">  
                            <input class="input-file" id="my-file" type="file" name="avatar">
                            <label tabindex="0" for="my-file" class="input-file-trigger btn btn-sm">Change profile picture</label>
                    </div>                                        
                  </div>
                </div>
                <div class="row row-cards">
                        @role('User')
                    <div class="col">
                        <div class="card">
                                <div class="card-body p-3 text-center">                                
                                <div class="h1 m-0">{{Auth::user()->tickets->count()}}</div>
                                        <div class="text-muted mb-4">Tickets Created</div>
                                      </div>
                              </div>
                            </div> 
                            @endrole                           
                </div>
                
            </div>
<div class="col-md-8">
    @card
        @cardHeader
            @slot('card_title') Edit {{ Auth::id() == $user->id ? 'Your Profile':$user->name }} @endslot
        @endcardHeader

        @cardBody              
                @include('backend.users._form')
                <div class="form-group">
                        <button type="submit" class="btn btn-md btn-primary">
                            {{ isset($user->id) ? 'Update':'Create'}}
                        </button>
                        <a href="{{route('users.index')}}" class="btn btn-secondary">Back</a> 
                        </div>
                
        @endcardBody

    @endcard
</div>
</div>

{!! Form::close() !!}
@endsection
@include('asset-partials.input-file')

resources/views/backend/users/index.blade.php
@extends('backend.master') 
@section('content')
@card
    @cardHeader
        @slot('card_title')<i class="fe fe-users"></i> Users @endslot
        @cardOptions
        <a class="btn btn-secondary btn-sm">Total: {{ $result->count() }} {{ str_plural('User', $result->count()) }}</a>

        @can('add_users')
        <a href="{{ route('users.create') }}" class="btn btn-primary btn-sm text-white"> <i class=""></i> Create</a> 
        @endcan 
        @endcardOptions
    @endcardHeader
    
    @cardBody
    <div class="table-responsive">
        @table(['class'=>'table card-table table-vcenter text-nowrap', 'id'=>'datatable'])
            <thead>
                <th>#</th>
                <th></th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Created At</th>
                @can('edit_users', 'delete_users')
                <th class="text-center">Actions</th>
                @endcan
            </thead>
            <tbody>
               @foreach($result as $key => $user)
               {{-- @if(Auth::user->hasRoles('Admin')) --}}
            <tr>
                <td>{{ ++$key }}</td>
                <td class="text-center"><div class="avatar d-block" style="background-image: url({{asset($user->profile->avatar)}})">                    
                    {{-- <span class="avatar-status {{$user->isOnline() ? 'bg-green':'bg-red'}}"></span>  --}}
                  </div></td>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>{{ $user->roles->implode('name', ', ') }}</td>
                <td>{{ $user->created_at->toDayDateTimeString() }}</td>
            
                @can('edit_users')
                <td class="text-center">
                    @can('edit_users')
                    <a href="{{ route('users.edit', ['id' => $user->id])  }}" class="btn btn-secondary btn-sm"><i class="fe fe-edit"></i> Edit</a>
                    @endcan
                    
                    @can('delete_users')                    
                        {!! Form::open( ['method' => 'delete', 'url' => route('users.destroy', ['id' => $user->id]), 'style' => 'display: inline', 'onSubmit' => 'return confirm("Are yous sure wanted to delete it?")']) !!}
                <button type="submit" class="btn-delete btn btn-sm btn-danger" style="visibility:{{Auth::id() == $user->id ? 'hidden':''}}">
                                <i class="fe fe-trash"></i> Delete
                            </button>
                        {!! Form::close() !!}
                    @endcan 
                </td>
                @endcan
            </tr>
            @endforeach             
            </tbody>
        @endtable
    </div>
    @endcardBody
@endcard
@include('asset-partials.datatables')
@endsection

resources/views/backend/users/profile.blade.php
@extends('backend.master') 
@section('content')
<form action="{{route('profile.update',['id'=> Auth::user()->id])}}" method="POST" enctype="multipart/form-data">
@csrf
<div class="row">
        <div class="col-md-4">
                <div class="card card-profile">
                  <div class="card-header" style="background-image: url({{asset('img/photos/bg-profile.jpg')}});"></div>
                  <div class="card-body text-center">
                    <img class="card-profile-img" src="{{asset($user->profile->avatar)}}">
                  <h3 class="mb-3">{{$user->name}}</h3>                    
                    <div class="input-file-container text-center">  
                            <input class="input-file" id="my-file" type="file" name="avatar">
                            <label tabindex="0" for="my-file" class="input-file-trigger btn btn-sm">Change profile picture</label>
                    </div>                                        
                  </div>
                </div>
                <div class="row row-cards">
                        @role('User')
                    <div class="col">
                        <div class="card">
                                {{-- <div class="card-body p-3 text-center">                                
                                <div class="h1 m-0">{{Auth::user()->tickets->count()}}</div>
                                        <div class="text-muted mb-4">Tickets Created</div>
                                      </div> --}}
                              </div>
                            </div> 
                            @endrole                           
                </div>
                
            </div>
<div class="col-md-8">
    @card
        @cardHeader
            @slot('card_title') Edit {{ Auth::id() == $user->id ? 'Your Profile':$user->name }} @endslot
        @endcardHeader

        @cardBody              
        <div class="form-group @if ($errors->has('name')) has-error @endif">
                {!! Form::label('name', 'Name') !!} 
                {!! Form::text('name', $user->name, ['class' => 'form-control', 'placeholder' => 'Name']) !!}
                @if ($errors->has('name'))
                <p class="help-block">{{ $errors->first('name') }}</p> @endif
            </div>
            
            <!-- email Form Input -->
            <div class="form-group @if ($errors->has('email')) has-error @endif">
                {!! Form::label('email', 'Email') !!} 
                {!! Form::text('email', $user->email, ['class' => 'form-control', 'placeholder' => 'Email'])
                !!} @if ($errors->has('email'))
                <p class="help-block">{{ $errors->first('email') }}</p> @endif
            </div>
            
            <!-- password Form Input -->
            <div class="form-group @if ($errors->has('password')) has-error @endif">
                {!! Form::label('password', 'Password') !!} 
                {!! Form::password('password', ['class' => 'form-control', 'placeholder' => 'Password'])
                !!} @if ($errors->has('password'))
                <p class="help-block">{{ $errors->first('password') }}</p> @endif
            </div>

                <div class="form-group">
                        <button type="submit" class="btn btn-md btn-primary">
                            {{ isset($user->id) ? 'Update':'Create'}}
                        </button>
                        <a href="{{route('users.index')}}" class="btn btn-secondary">Back</a> 
                        </div>
                
        @endcardBody
    @endcard
</div>
</div>

</form>
@endsection
@include('asset-partials.input-file')